### ISSUE TITLE
Does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by eagleofnorth** [mriza/XMind-Linux-Installer#6]
Script works fine in Ubuntu 16.04 but not in Ubuntu 18.04. 

Install script says inatallation went fine, but when opening XMind it crash with message: 

An error has occured. See the log file /home/myuser/workspace/.metadata/.log.

**Comment by Juba19** [comment]
Hello, 

Same issue i'm working on Ubuntu 18.04 with Xmind and that's how i resolve it :

Write on your terminal : sudo gedit "/opt/xmind/XMind_amd64/XMind.ini"

And add this 

-vmargs
--add-modules=java.se.ee
-Dosgi.requiredJavaVersion=1.8
-Xms256m
-Xmx1024m

So that's what it will be look's like :

-configuration
@user.home/.configuration
-data
@user.home/workspace
-startup
/opt/xmind/plugins/org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar
--launcher.library
/opt/xmind/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.400.v20160518-1444
--launcher.defaultAction
openFile
--launcher.GTK_version
2
-eclipse.keyring
@user.home/.xmind/secure_storage_linux
-vmargs
--add-modules=java.se.ee
-Dosgi.requiredJavaVersion=1.8
-Xms256m
-Xmx1024m
-Dfile.encoding=UTF-8

Regards

**Comment by harrypalheta** [comment]
@Juba19 Thanks a lot. It's working perfectly in the Fedora 27.

**Comment by mriza** [comment]
please try the new update https://github.com/mriza/XMind-Linux-Installer/commit/db575d5050f08878257076daef645d889b97479c
thank you @Juba19
